spring.application.name=Calories-Tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/calorie_tracker
spring.datasource.username=postgres
spring.datasource.password=Vietnam30102007@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080